{ 
    controls: {
        "page":{"background_color": "#9f9f9f",
         "background_image_centered": 1,
         "border": 0,
         "border_color": "#666666",
         "border_style": "solid",
         "canvas_color": "#ffffff",
         "h": 672,
         "id": "page",
         "image": { "id": "", "w": 0, "h": 0 },
         "show_arrows": 0,
         "show_toc": 0,
         "skin": "book_flat",
         "toc_position": "window_top",
         "toc_structure": "tabbedflat",
         "type": "page",
         "version": "8.3.0.065",
         "w": 1024}
    ,"CTL55E11B1D758BF28F":{
        "h": 50,
        "hide_scrollbars": 1,
        "id": "CTL55E11B1D758BF28F",
        "locked": 0,
        "name": "title",
        "text": "",
        "type": "text",
        "w": 560,
        "x": 135,
        "y": 48,
        "z": 7}
    ,"CTLF3F58EB34EA74498":{
        "h": 154,
        "id": "CTLF3F58EB34EA74498",
        "name": "task",
        "text": "",
        "type": "text",
        "w": 560,
        "x": 135,
        "y": 98,
        "z": 8}
    ,"CTL696312184D3B0D98":{
        "h": 194,
        "id": "CTL696312184D3B0D98",
        "name": "media_preview",
        "type": "image",
        "w": 256,
        "x": 720,
        "y": 48,
        "z": 33}
    ,"CTLF3F58EB34EA744998":{
        "h": 154,
        "id": "CTLF3F58EB34EA74499",
        "name": "quiz_text",
        "text": "",
        "type": "fibquiz",
        "quiz_type" : "qt_text",
         "w": 685,
         "x": 135,
         "y": 252,
         "z": 11}

    ,"CTL864152FE2A7E6187":{"action_align_gridquiz": "Left",
     "action_border_width": 0,
     "action_dist_to_next_matchquiz": 8,
     "action_dist_to_next_mchoice": 8,
     "action_h_matchquiz": 40,
     "action_size_gridquiz": 36,
     "action_size_mchoice": 26,
     "action_slider_border_radius_scalequiz": 0,
     "action_slider_border_width_scalequiz": 0,
     "action_valign_gridquiz": "middle",
     "action_valign_mchoice": "middle",
     "id": "CTL864152FE2A7E6187",
     "name": "quiz_element",
     "padding": 0,
     "scale_thickness": 0,
     "slider_h": 0,
     "slider_w": 0,
     "type": "quiz_template",
     "w": 0,
     "h": 0,
     "x": 0,
     "y": 0,
     "z": 0}

    }
}