{
"global_params":{
}
,
"user_header":{
"audio_ext":".wav",
"author":"I513536",
"comment":"",
"language":"en-US",
"mastery_score_percent":"80",
"max_score_percent":"100",
"shelftype":"standard",
"title":"Portal - Forms",
"version":"10.5.9"}
,
"tourstops":[
{
"index":0,
"title":"Start",
"audio":"",
"uid":"TS_F6A08CE757A04D18B0902D1C80840A98",
"jumpable":false,
"visible":false,
"callable":false,
"duration":9,
"audio_duration":0,
"macros":[
{
"macro_template":"start_unit",
"time":0,
"duration":10,
"uid":"MAC_CCFF812F9132BBA8",
"possible_points":57,
"mastery_score":46,
"scaling":"150%",
"task_text":"",
"task_width":240,
"task_height":0,
"task_orientation":"NE",
"task_bgcolor":"#ffffb7",
"in_practice":false,
"in_test":true,
"config_templates":"<CTRoot><CTFile name=\"Standard\">2949087471<\/CTFile><\/CTRoot>"}
]
}
,{
"index":1,
"title":"Client Portal - Home Page - Brave",
"audio":"",
"uid":"TS_8F270BBC5AFB43D29074869FF3A48C76",
"jumpable":true,
"visible":false,
"callable":false,
"duration":29,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_D0D167C9E570F886",
"new_step":"Client Portal - Home Page - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"explanation_long",
"time":9,
"duration":10,
"uid":"MAC_9F6F10C110F0D89",
"all_like_demo":false,
"explanation_d":"<p>In this Portal demonstration, we will review how to view and edit forms.<\/p>\n",
"explanation_p":"<p>In this Portal demonstration, we will review how to view and edit forms.<\/p>\n",
"type":"info",
"bubblestyle_d":"sap_gold",
"b_width":288,
"b_height":210,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
,{
"macro_template":"click",
"time":19,
"duration":10,
"uid":"MAC_DDFDAD1B9F24E6A1",
"explanation_d":"<p><span style=\"font-weight:bold; \">Scroll Down<\/span>&nbsp;to review the Home page.<\/p>\n",
"explanation_p":"<p><span style=\"font-weight:bold; \">Scroll Down<\/span>&nbsp;to review the Home page.<\/p>\n",
"fieldname":"",
"fieldicon":"",
"action":"drag",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"sap_gold",
"b_width":202,
"b_height":144,
"orientation":"W",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.978378",
"y":"0.453254"}
,
"DocXY":{
"x":"0.978378",
"y":"0.453254"}
}
,
"b_duration":4,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"SW",
"position_bu":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":0,
"y":15}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":1585,
"top":177}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":1596,
"top":287,
"width":0,
"height":0}
,
"ctl_rect":{
"left":1566,
"top":1,
"width":30,
"height":819}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":"",
"ctl_disabled":false}
]
}
,{
"index":2,
"title":"Client Portal - Home Page - Brave",
"audio":"",
"uid":"TS_C1978DC033324746A3249FDB5EFF0C7C",
"jumpable":true,
"visible":false,
"callable":false,
"duration":39,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_9D6A2E52BC74E88C",
"new_step":"Client Portal - Home Page - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"free_highlight",
"time":9,
"duration":10,
"macro_comment":"",
"uid":"MAC_AFFE6AE92B48A9A9",
"obj_name":"highlight1",
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"highlight_rgb":"#858585",
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"in_guided":true,
"in_pres":true,
"highlight_off":false,
"ctl_rect":{
"left":543,
"top":51,
"width":192,
"height":36}
}
,{
"macro_template":"explanation_long",
"time":19,
"duration":10,
"uid":"MAC_87AACCBCF34F3CBE",
"all_like_demo":false,
"explanation_d":"<p>The Home Page contains a link to our Welcome Kit, and recommendations on how to begin the planning process.<\/p>\n",
"explanation_p":"<p>The Home Page contains a link to our Welcome Kit, and recommendations on how to begin the planning process.<\/p>\n",
"type":"info",
"bubblestyle_d":"sap_gold",
"b_width":444,
"b_height":285,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
,{
"macro_template":"click",
"time":29,
"duration":10,
"uid":"MAC_D2DA78B53AD0D89A",
"explanation_d":"<p><span style=\"font-weight:bold; \">Scroll Down<\/span>&nbsp;to continue reviewing the Home page.<\/p>\n",
"explanation_p":"<p><span style=\"font-weight:bold; \">Scroll Down<\/span>&nbsp;to continue reviewing the Home page.<\/p>\n",
"fieldname":"",
"fieldicon":"",
"action":"drop",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"sap_gold",
"b_width":219,
"b_height":171,
"orientation":"W",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.981201",
"y":"0.611643"}
,
"DocXY":{
"x":"0.981201",
"y":"0.611643"}
}
,
"b_duration":4,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"NW",
"position_bu":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":0,
"y":-15}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":1584,
"top":722}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":1566,
"top":3,
"width":30,
"height":820}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":3,
"title":"Client Portal - Home Page - Brave",
"audio":"",
"uid":"TS_1233B86FB4734465B377AD135501A11F",
"jumpable":true,
"visible":false,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_52B076E96FEDE489",
"new_step":"Client Portal - Home Page - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_38723411708D26B0",
"explanation_d":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>Click <span style=\"font-weight:bold; \">$#{fieldname}&nbsp;$I{fieldicon}<\/span>.<\/p>\n",
"fieldname":"",
"fieldicon":"fieldicon_10.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"sap_gold",
"b_width":150,
"b_height":40,
"orientation":"SW",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.562951",
"y":"0.278508"}
,
"DocXY":{
"x":"0.562951",
"y":"0.278508"}
}
,
"b_duration":4,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"SW",
"position_bu":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":4}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":893,
"top":180}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":840,
"top":150,
"width":138,
"height":72}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":4,
"title":"Client Portal - Plan My Event - Brave",
"audio":"",
"uid":"TS_36BC0F2CEBAF4D03A45610C9C92953A0",
"jumpable":true,
"visible":false,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_DCD0A0947D9065AD",
"new_step":"Client Portal - Plan My Event - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_3E18FCC603E778D",
"explanation_d":"<p><span style=\"font-weight:bold; \">Scroll Down<\/span>&nbsp;to access the planning tools.<\/p>\n",
"explanation_p":"<p><span style=\"font-weight:bold; \">Scroll Down<\/span>&nbsp;to access the planning tools.<\/p>\n",
"fieldname":"",
"fieldicon":"",
"action":"drag",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"sap_gold",
"b_width":187,
"b_height":129,
"orientation":"W",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.983078",
"y":"0.338567"}
,
"DocXY":{
"x":"0.983078",
"y":"0.338567"}
}
,
"b_duration":4,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"NW",
"position_bu":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":0,
"y":-15}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":1586,
"top":374}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":1597,
"top":484,
"width":0,
"height":0}
,
"ctl_rect":{
"left":1566,
"top":9,
"width":30,
"height":814}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":"",
"ctl_disabled":false}
]
}
,{
"index":5,
"title":"Client Portal - Plan My Event - Brave",
"audio":"",
"uid":"TS_E390363B8298492FA21036C4D6C3F4AC",
"jumpable":true,
"visible":false,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_751048AF740264AE",
"new_step":"Client Portal - Plan My Event - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_22D51E88C8B2E58D",
"explanation_d":"<p>To access the forms associated with your event, <span style=\"font-weight:bold; \">Click<\/span> <span style=\"font-weight:bold; \">$I{fieldicon}.<\/span><\/p>\n",
"explanation_p":"<p>To access the forms associated with your event, <span style=\"font-weight:bold; \">Click<\/span> <span style=\"font-weight:bold; \">$I{fieldicon}.<\/span><\/p>\n",
"fieldname":"",
"fieldicon":"fieldicon_18.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"sap_gold",
"b_width":235,
"b_height":124,
"orientation":"NW",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":-4}
}
,
"b_duration":4,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"NW",
"position_bu":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":-4}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":674,
"top":637}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":619,
"top":559,
"width":138,
"height":183}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":6,
"title":"Client Portal - Plan My Event - Brave",
"audio":"",
"uid":"TS_EA31BB87D2A54358AF52CCBA388405F4",
"jumpable":true,
"visible":false,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_30393C7728C716B7",
"new_step":"Client Portal - Plan My Event - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_6C443E7559641A9E",
"explanation_d":"<p>Choose a form and <span style=\"font-weight:bold; \">Click<\/span> <span style=\"font-weight:bold; \">$#{fieldname} $I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>Choose a form and <span style=\"font-weight:bold; \">Click<\/span> <span style=\"font-weight:bold; \"> $I{fieldicon}<\/span>.<\/p>\n",
"fieldname":"",
"fieldicon":"fieldicon.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"sap_gold",
"b_width":150,
"b_height":40,
"orientation":"NW",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.598657",
"y":"0.560678"}
,
"DocXY":{
"x":"0.598657",
"y":"0.560678"}
}
,
"b_duration":4,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"NW",
"position_bu":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":-4}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":994,
"top":483}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":950,
"top":462,
"width":96,
"height":38}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":7,
"title":"Client Portal - Planning Forms - Brave",
"audio":"",
"uid":"TS_7F09412C46704BF5ADAD00419FCD6167",
"jumpable":true,
"visible":false,
"callable":false,
"duration":49,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_F526AFA7B91AB9A4",
"new_step":"Client Portal - Planning Forms - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"free_highlight",
"time":9,
"duration":10,
"macro_comment":"",
"uid":"MAC_876B4DC199B42E8D",
"obj_name":"highlight1",
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"highlight_rgb":"#858585",
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"in_guided":true,
"in_pres":true,
"highlight_off":false,
"ctl_rect":{
"left":1237,
"top":687,
"width":153,
"height":69}
}
,{
"macro_template":"free_highlight",
"time":19,
"duration":10,
"macro_comment":"",
"uid":"MAC_B5EBD56BDD7319A3",
"obj_name":"highlight1",
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"highlight_rgb":"#858585",
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"in_guided":true,
"in_pres":true,
"highlight_off":false,
"ctl_rect":{
"left":703,
"top":784,
"width":163,
"height":39}
}
,{
"macro_template":"explanation_long",
"time":29,
"duration":10,
"uid":"MAC_37A3EDE10324A96",
"all_like_demo":false,
"explanation_d":"<p>The Portal's Auto-Save feature will automatically save any changes every 60 seconds, however, it's recommended to <span style=\"font-weight:bold; \">Click<\/span> the <span style=\"font-weight:bold; \">Save Changes<\/span> button frequently just to be safe.<\/p>\n",
"explanation_p":"<p>The Portal's Auto-Save feature will automatically save any changes every 60 seconds, however, it's recommended to <span style=\"font-weight:bold; \">Click<\/span> the <span style=\"font-weight:bold; \">Save Changes<\/span> button frequently just to be safe.<\/p>\n",
"type":"info",
"bubblestyle_d":"sap_gold",
"b_width":636,
"b_height":198,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
,{
"macro_template":"click",
"time":39,
"duration":10,
"uid":"MAC_30E9BA1BA2CA11BF",
"explanation_d":"<p><span style=\"font-weight:bold; \">Scroll Down<\/span> to begin editing the form.<\/p>\n",
"explanation_p":"<p><span style=\"font-weight:bold; \">Scroll Down<\/span> to begin editing the form.<\/p>\n",
"fieldname":"",
"fieldicon":"fieldicon_23.png",
"action":"drag",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"sap_gold",
"b_width":198,
"b_height":147,
"orientation":"WS",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.984955",
"y":"0.387732"}
,
"DocXY":{
"x":"0.984955",
"y":"0.387732"}
}
,
"b_duration":4,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"SW",
"position_bu":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":4}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":1579,
"top":59}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":1572,
"top":10,
"width":21,
"height":807}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":8,
"title":"Client Portal - Planning Forms - Brave",
"audio":"",
"uid":"TS_7139F9FA68B04D18ADDD4AEDA7881074",
"jumpable":true,
"visible":false,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_F46E11B4148D5EBE",
"new_step":"Client Portal - Planning Forms - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"explanation_long",
"time":9,
"duration":10,
"uid":"MAC_A0D1518C88BA50AF",
"all_like_demo":false,
"explanation_d":"<p>Fill out as much information as possible in these forms, but if something does not apply to your event, or if you are unsure, leave it blank. Keep in mind you can also come back to these forms later to fill in any missing information or to make changes.<\/p>\n",
"explanation_p":"<p>Fill out as much information as possible in these forms, but if something does not apply to your event, or if you are unsure, leave it blank. Keep in mind you can also come back to these forms later to fill in any missing information or to make changes.<\/p>\n",
"type":"info",
"bubblestyle_d":"sap_gold",
"b_width":624,
"b_height":348,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.458625",
"y":"0.587976"}
,
"DocXY":{
"x":"0.458625",
"y":"0.587976"}
}
,
"b_duration":-1,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
]
}
,{
"index":9,
"title":"Client Portal - Planning Forms - Brave",
"audio":"",
"uid":"TS_BE430A9BFA2E4F6E9FEB226450481653",
"jumpable":true,
"visible":false,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_CA5A5D43696DC388",
"new_step":"Client Portal - Planning Forms - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_2526F3E00BCB78BC",
"explanation_d":"<p>For text fields, simply <span style=\"font-weight:bold; \">Click<\/span>&nbsp;inside the box, and <span style=\"font-weight:bold; \">Type<\/span>.<\/p>\n",
"explanation_p":"<p>For text fields, simply <span style=\"font-weight:bold; \">Click<\/span>&nbsp;inside the box, and <span style=\"font-weight:bold; \">Type<\/span>.<\/p>\n",
"fieldname":"",
"fieldicon":"fieldicon.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"sap_gold",
"b_width":150,
"b_height":40,
"orientation":"SW",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":4}
}
,
"b_duration":4,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"SW",
"position_bu":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":4}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":914,
"top":70}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":888,
"top":55,
"width":417,
"height":35}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":10,
"title":"Client Portal - Planning Forms - Brave",
"audio":"",
"uid":"TS_0F32EA8B82BD48DA8A31C37455FC9544",
"jumpable":true,
"visible":false,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_91D545EFC9475ABF",
"new_step":"Client Portal - Planning Forms - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"input_text",
"time":9,
"duration":10,
"uid":"MAC_44E8B2FC5EBDC096",
"explanation_d":"<p>Let's <span style=\"font-weight:bold; \">Type<\/span> in the Bride's name.<\/p>\n",
"explanation_p":"<p>Let's <span style=\"font-weight:bold; \">Type<\/span> in the Bride's name.<\/p>\n",
"fieldname":"",
"fieldicon":"",
"ctl_init_text":"",
"text_d":"Jane Doe",
"regexp":"\/.{1}\/",
"confirmation_tab":false,
"confirmation_enter":false,
"affirmation_button":false,
"position_h":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"btn_rect":{
"left":20,
"top":20,
"width":24,
"height":24}
,
"btn_cursor_hand":true,
"btn_is_button":true,
"bubblestyle_d":"sap_gold",
"b_width":180,
"b_height":40,
"orientation":"SW",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":4}
}
,
"b_duration":4,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"SW",
"position_bu":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":4}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"set_focus":true,
"animated":true,
"screenshot_rect":{
"left":887,
"top":55,
"width":420,
"height":33}
,
"exec_mouse":false,
"ctl_rect":{
"left":887,
"top":55,
"width":420,
"height":33}
,
"ctl_password":false,
"is_textarea":false,
"ctl_font_family":"",
"ctl_font_size":9,
"ctl_font_bold":false,
"ctl_font_italic":false,
"ctl_font_underline":false,
"ctl_font_color":"#000000",
"ctl_bg_color":"#ffffff"}
]
}
,{
"index":11,
"title":"Client Portal - Planning Forms - Brave",
"audio":"",
"uid":"TS_7A46FD7C6CB6466BA4BD7A20C2625E00",
"jumpable":true,
"visible":false,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_90F003E455D389AF",
"new_step":"Client Portal - Planning Forms - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"input_text",
"time":9,
"duration":10,
"uid":"MAC_4D1722832135A295",
"explanation_d":"<p>Now we'll <span style=\"font-weight:bold; \">Type<\/span>&nbsp;the Groom's name.<\/p>\n",
"explanation_p":"<p>Now we'll <span style=\"font-weight:bold; \">Type<\/span>&nbsp;the Groom's name.<\/p>\n",
"fieldname":"",
"fieldicon":"",
"ctl_init_text":"",
"text_d":"John Doe",
"regexp":"\/.{1}\/",
"confirmation_tab":false,
"confirmation_enter":false,
"affirmation_button":false,
"position_h":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"btn_rect":{
"left":20,
"top":20,
"width":24,
"height":24}
,
"btn_cursor_hand":true,
"btn_is_button":true,
"bubblestyle_d":"sap_gold",
"b_width":180,
"b_height":40,
"orientation":"SW",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":4}
}
,
"b_duration":4,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"SW",
"position_bu":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":4}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"set_focus":true,
"animated":true,
"screenshot_rect":{
"left":887,
"top":102,
"width":420,
"height":33}
,
"exec_mouse":false,
"ctl_rect":{
"left":887,
"top":102,
"width":420,
"height":33}
,
"ctl_password":false,
"is_textarea":false,
"ctl_font_family":"",
"ctl_font_size":9,
"ctl_font_bold":false,
"ctl_font_italic":false,
"ctl_font_underline":false,
"ctl_font_color":"#000000",
"ctl_bg_color":"#ffffff"}
]
}
,{
"index":12,
"title":"Client Portal - Planning Forms - Brave",
"audio":"",
"uid":"TS_F0A46095B65E4ADE85106763EC31C670",
"jumpable":true,
"visible":false,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_54C81889A7E31F8D",
"new_step":"Client Portal - Planning Forms - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"input_text",
"time":9,
"duration":10,
"uid":"MAC_514398E1BD46DA8A",
"explanation_d":"<p>We will <span style=\"font-weight:bold; \">Type<\/span>&nbsp;in the estimated guest arrival time.<\/p>\n",
"explanation_p":"<p>We will <span style=\"font-weight:bold; \">Type<\/span>&nbsp;in the estimated guest arrival time.<\/p>\n",
"fieldname":"",
"fieldicon":"",
"ctl_init_text":"",
"text_d":"4pm",
"regexp":"\/.{1}\/",
"confirmation_tab":false,
"confirmation_enter":false,
"affirmation_button":false,
"position_h":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"btn_rect":{
"left":20,
"top":20,
"width":24,
"height":24}
,
"btn_cursor_hand":true,
"btn_is_button":true,
"bubblestyle_d":"sap_gold",
"b_width":180,
"b_height":40,
"orientation":"SW",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":4}
}
,
"b_duration":4,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"SW",
"position_bu":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":4}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"set_focus":true,
"animated":true,
"screenshot_rect":{
"left":887,
"top":149,
"width":420,
"height":33}
,
"exec_mouse":false,
"ctl_rect":{
"left":887,
"top":149,
"width":420,
"height":33}
,
"ctl_password":false,
"is_textarea":false,
"ctl_font_family":"",
"ctl_font_size":9,
"ctl_font_bold":false,
"ctl_font_italic":false,
"ctl_font_underline":false,
"ctl_font_color":"#000000",
"ctl_bg_color":"#ffffff"}
]
}
,{
"index":13,
"title":"Client Portal - Planning Forms - Brave",
"audio":"",
"uid":"TS_B7F5EE0B0D0849D5A895411A7D8ABEF7",
"jumpable":true,
"visible":false,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_45A95712176231BF",
"new_step":"Client Portal - Planning Forms - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"input_text",
"time":9,
"duration":10,
"uid":"MAC_3FE1E0CABFCD3A4",
"explanation_d":"<p>We can also <span style=\"font-weight:bold; \">Type <\/span>in the estimated number of guests.<\/p>\n",
"explanation_p":"<p>We can also <span style=\"font-weight:bold; \">Type <\/span>in the estimated number of guests.<\/p>\n",
"fieldname":"",
"fieldicon":"",
"ctl_init_text":"",
"text_d":"100",
"regexp":"\/.{1}\/",
"confirmation_tab":false,
"confirmation_enter":false,
"affirmation_button":false,
"position_h":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"btn_rect":{
"left":20,
"top":20,
"width":24,
"height":24}
,
"btn_cursor_hand":true,
"btn_is_button":true,
"bubblestyle_d":"sap_gold",
"b_width":180,
"b_height":40,
"orientation":"SW",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":4}
}
,
"b_duration":4,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"SW",
"position_bu":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":4}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"set_focus":true,
"animated":true,
"screenshot_rect":{
"left":887,
"top":196,
"width":420,
"height":33}
,
"exec_mouse":false,
"ctl_rect":{
"left":887,
"top":196,
"width":420,
"height":33}
,
"ctl_password":false,
"is_textarea":false,
"ctl_font_family":"",
"ctl_font_size":9,
"ctl_font_bold":false,
"ctl_font_italic":false,
"ctl_font_underline":false,
"ctl_font_color":"#000000",
"ctl_bg_color":"#ffffff"}
]
}
,{
"index":14,
"title":"Client Portal - Planning Forms - Brave",
"audio":"",
"uid":"TS_A90F51D3B8AD4DB0B64154A31F949618",
"jumpable":true,
"visible":false,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_386B0FD5E332FA92",
"new_step":"Client Portal - Planning Forms - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_8DFE750C73D047BD",
"explanation_d":"<p>Some fields contain lists of responses to choose from. <span style=\"font-weight:bold; \">Click<\/span> the <span style=\"font-weight:bold; \">$#{fieldname} $I{fieldicon}<\/span> button to open the dropdown list.<\/p>\n",
"explanation_p":"<p>Some fields contain lists of responses to choose from. <span style=\"font-weight:bold; \">Click<\/span> the <span style=\"font-weight:bold; \">$#{fieldname} $I{fieldicon}<\/span> button to open the dropdown list.<\/p>\n",
"fieldname":"",
"fieldicon":"52339D7846A4ACB0.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"sap_gold",
"b_width":304,
"b_height":181,
"orientation":"NW",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.608057",
"y":"0.467811"}
,
"DocXY":{
"x":"0.608057",
"y":"0.467811"}
}
,
"b_duration":4,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"NW",
"position_bu":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":-4}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":978,
"top":407}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":883,
"top":394,
"width":108,
"height":25}
,
"cursor_hand":true,
"ctl_button":true,
"ctl_tooltip":""}
]
}
,{
"index":15,
"title":"Client Portal - Planning Forms - Brave",
"audio":"",
"uid":"TS_F1B61889E6FA4298BA68C43F543FA5BE",
"jumpable":true,
"visible":false,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_869423C5CED6A48C",
"new_step":"Client Portal - Planning Forms - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_A89BC31E5D0C54AD",
"explanation_d":"<p><span style=\"font-weight:bold; \">Click<\/span> to choose an option from the list.<\/p>\n",
"explanation_p":"<p><span style=\"font-weight:bold; \">Click<\/span> to choose an option from the list.<\/p>\n",
"fieldname":"",
"fieldicon":"fieldicon_28.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"sap_gold",
"b_width":150,
"b_height":40,
"orientation":"NW",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":-4}
}
,
"b_duration":4,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"NW",
"position_bu":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":-4}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":915,
"top":460}
,
"click_count":1,
"exec_mouse":false,
"ctl_rect":{
"left":892,
"top":448,
"width":99,
"height":22}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":16,
"title":"Client Portal - Planning Forms - Brave",
"audio":"",
"uid":"TS_A5D743B3BC0F4C61AFBA99A69171954A",
"jumpable":true,
"visible":false,
"callable":false,
"duration":29,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_2779307ADE5024AE",
"new_step":"Client Portal - Planning Forms - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"free_highlight",
"time":9,
"duration":10,
"macro_comment":"",
"uid":"MAC_A173A6F09466F094",
"obj_name":"highlight1",
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"highlight_rgb":"#858585",
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"in_guided":true,
"in_pres":true,
"highlight_off":false,
"ctl_rect":{
"left":259,
"top":445,
"width":1054,
"height":100}
}
,{
"macro_template":"explanation_long",
"time":19,
"duration":10,
"uid":"MAC_A1C471010FD406BA",
"all_like_demo":false,
"explanation_d":"<p>Some of the options you choose may open additional fields that allow you to provide further details.<\/p>\n",
"explanation_p":"<p>Some of the options you choose may open additional fields that allow you to provide further details.<\/p>\n",
"type":"info",
"bubblestyle_d":"sap_gold",
"b_width":543,
"b_height":183,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
]
}
,{
"index":17,
"title":"Client Portal - Planning Forms - Brave",
"audio":"",
"uid":"TS_F27F7EAEA474445FA73F272E23F308B3",
"jumpable":true,
"visible":false,
"callable":false,
"duration":9,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_EA8FD188D2980995",
"new_step":"Client Portal - Planning Forms - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
]
}
,{
"index":18,
"title":"Client Portal - Planning Forms - Brave",
"audio":"",
"uid":"TS_E8C81A96E7BD42FAB12E565E1F9272FE",
"jumpable":true,
"visible":false,
"callable":false,
"duration":29,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_51537F85D839FF90",
"new_step":"Client Portal - Planning Forms - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"free_highlight",
"time":9,
"duration":10,
"macro_comment":"",
"uid":"MAC_14539F9650B5AAAB",
"obj_name":"highlight1",
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"highlight_rgb":"#858585",
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"in_guided":true,
"in_pres":true,
"highlight_off":false,
"ctl_rect":{
"left":256,
"top":240,
"width":1053,
"height":192}
}
,{
"macro_template":"explanation_long",
"time":19,
"duration":10,
"uid":"MAC_285A9D72868F6B8D",
"all_like_demo":false,
"explanation_d":"<p>Most form sections have an Additional Notes area where you can provide notes, comments, or more information.<\/p>\n",
"explanation_p":"<p>Most form sections have an Additional Notes area where you can provide notes, comments, or more information.<\/p>\n",
"type":"info",
"bubblestyle_d":"sap_gold",
"b_width":621,
"b_height":147,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.500923",
"y":"0.500603"}
,
"DocXY":{
"x":"0.500923",
"y":"0.500603"}
}
,
"b_duration":-1,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
]
}
,{
"index":19,
"title":"Client Portal - Planning Forms - Brave",
"audio":"",
"uid":"TS_1A9083E5690943E589CBF6EB27E12468",
"jumpable":true,
"visible":false,
"callable":false,
"duration":9,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_D1FE23C95F17B9A0",
"new_step":"Client Portal - Planning Forms - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
]
}
,{
"index":20,
"title":"Client Portal - Planning Forms - Brave",
"audio":"",
"uid":"TS_DB60963EE89C45A3BF00DC228563AF9A",
"jumpable":true,
"visible":false,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_F9CEA38A167393B1",
"new_step":"Client Portal - Planning Forms - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_5236543578E6049F",
"explanation_d":"<p>When you are finished editing the form, <span style=\"font-weight:bold; \">Click<\/span> <span style=\"font-weight:bold; \">$#{fieldname} $I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>When you are finished editing the form, <span style=\"font-weight:bold; \">Click<\/span> <span style=\"font-weight:bold; \"> $I{fieldicon}<\/span>.<\/p>\n",
"fieldname":"",
"fieldicon":"fieldicon.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"sap_gold",
"b_width":150,
"b_height":40,
"orientation":"NW",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":-4}
}
,
"b_duration":4,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"NW",
"position_bu":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":-4}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":759,
"top":690}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":710,
"top":672,
"width":151,
"height":42}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":21,
"title":"Client Portal - Plan My Event - Brave",
"audio":"",
"uid":"TS_304B5DA9CE464F9488F36B55A50DE216",
"jumpable":true,
"visible":false,
"callable":false,
"duration":29,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_180A3EAB9BDD07A4",
"new_step":"Client Portal - Plan My Event - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"free_highlight",
"time":9,
"duration":10,
"macro_comment":"",
"uid":"MAC_DAACC16BFEB4B286",
"obj_name":"highlight1",
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"highlight_rgb":"#858585",
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"in_guided":true,
"in_pres":true,
"highlight_off":false,
"ctl_rect":{
"left":201,
"top":723,
"width":1168,
"height":100}
}
,{
"macro_template":"explanation_long",
"time":19,
"duration":10,
"uid":"MAC_27DA3FA020BF1E8F",
"all_like_demo":false,
"explanation_d":"<p>A message will appear to confirm that the form changes have been saved successfully.<\/p>\n",
"explanation_p":"<p>A message will appear to confirm that the form changes have been saved successfully.<\/p>\n",
"type":"info",
"bubblestyle_d":"sap_gold",
"b_width":522,
"b_height":150,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
]
}
,{
"index":22,
"title":"Client Portal - Plan My Event - Brave",
"audio":"",
"uid":"TS_BCC7D6150B164B8193A6BD0B05EC8DC2",
"jumpable":true,
"visible":false,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_2EF1967A304945B4",
"new_step":"Client Portal - Plan My Event - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_E0E5D7537096C4B9",
"explanation_d":"<p>To view the form, scroll down and <span style=\"font-weight:bold; \">Click<\/span> <span style=\"font-weight:bold; \">$#{fieldname} $I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>To view the form, scroll down and <span style=\"font-weight:bold; \">Click<\/span> <span style=\"font-weight:bold; \"> $I{fieldicon}<\/span>.<\/p>\n",
"fieldname":"",
"fieldicon":"fieldicon_34.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"sap_gold",
"b_width":150,
"b_height":40,
"orientation":"NW",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":-4}
}
,
"b_duration":4,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"NW",
"position_bu":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":-4}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":677,
"top":619}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":624,
"top":561,
"width":130,
"height":178}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":23,
"title":"Client Portal - Plan My Event - Brave",
"audio":"",
"uid":"TS_3BD5B664610944E7B9BA44A532F3B472",
"jumpable":true,
"visible":false,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_ED80A816D4F8FB8D",
"new_step":"Client Portal - Plan My Event - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_7393A93797E125A6",
"explanation_d":"<p><span style=\"font-weight:bold; \">Scroll Down<\/span>&nbsp;to view the list of forms.<\/p>\n",
"explanation_p":"<p><span style=\"font-weight:bold; \">Scroll Down<\/span>&nbsp;to view the list of forms.<\/p>\n",
"fieldname":"",
"fieldicon":"",
"action":"drop",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"sap_gold",
"b_width":150,
"b_height":40,
"orientation":"W",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.982132",
"y":"0.686275"}
,
"DocXY":{
"x":"0.982132",
"y":"0.686275"}
}
,
"b_duration":4,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"NW",
"position_bu":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":0,
"y":-15}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":1568,
"top":609}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":1573,
"top":6,
"width":18,
"height":817}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":24,
"title":"Client Portal - Plan My Event - Brave",
"audio":"",
"uid":"TS_CCA676658A374B5EB26A0B39EEC7DC7E",
"jumpable":true,
"visible":false,
"callable":false,
"duration":19,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_3A83D67C636079A2",
"new_step":"Client Portal - Plan My Event - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"click",
"time":9,
"duration":10,
"uid":"MAC_D2F8EA362DA06DBF",
"explanation_d":"<p>Find the form, then <span style=\"font-weight:bold; \">Click<\/span> <span style=\"font-weight:bold; \">$#{fieldname} $I{fieldicon}<\/span>.<\/p>\n",
"explanation_p":"<p>Find the form, then <span style=\"font-weight:bold; \">Click<\/span> <span style=\"font-weight:bold; \"> $I{fieldicon}<\/span>.<\/p>\n",
"fieldname":"",
"fieldicon":"fieldicon.png",
"action":"lclick",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"sap_gold",
"b_width":150,
"b_height":40,
"orientation":"NW",
"position_b":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":-4}
}
,
"b_duration":4,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"NW",
"position_bu":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":-4}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":1106,
"top":477}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":1069,
"top":462,
"width":104,
"height":38}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":25,
"title":"Client Portal - Planning Forms - Brave",
"audio":"",
"uid":"TS_AC03496836BE4D5FBCF342ECA7FBD8BB",
"jumpable":true,
"visible":false,
"callable":false,
"duration":39,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_EC36DC1F84E7A0A4",
"new_step":"Client Portal - Planning Forms - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"free_highlight",
"time":9,
"duration":10,
"macro_comment":"",
"uid":"MAC_C5EE56F29A102194",
"obj_name":"highlight1",
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"highlight_rgb":"#858585",
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"in_guided":true,
"in_pres":true,
"highlight_off":false,
"ctl_rect":{
"left":1212,
"top":690,
"width":175,
"height":60}
}
,{
"macro_template":"explanation_long",
"time":19,
"duration":10,
"uid":"MAC_BFE7C71B1EDF618D",
"all_like_demo":false,
"explanation_d":"<p>Note that you can use the button to <span style=\"font-weight:bold; \">Print<\/span> the planning form.<\/p>\n",
"explanation_p":"<p>Note that you can use the button to <span style=\"font-weight:bold; \">Print<\/span> the planning form.<\/p>\n",
"type":"info",
"bubblestyle_d":"sap_gold",
"b_width":462,
"b_height":168,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
,{
"macro_template":"click",
"time":29,
"duration":10,
"uid":"MAC_C0D538A5B98318AF",
"explanation_d":"<p><span style=\"font-weight:bold; \">Scroll Down<\/span> to view the form.<\/p>\n",
"explanation_p":"<p><span style=\"font-weight:bold; \">Scroll Down<\/span> to view the form.<\/p>\n",
"fieldname":"",
"fieldicon":"fieldicon_38.png",
"action":"drag",
"ctrl_key":false,
"alt_key":false,
"shift_key":false,
"position_h":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"0.000000"}
,
"XY2":{
"x":"1.000000",
"y":"1.000000"}
}
,
"bubblestyle_d":"sap_gold",
"b_width":150,
"b_height":120,
"orientation":"W",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.972717",
"y":"0.475105"}
,
"DocXY":{
"x":"0.972717",
"y":"0.475105"}
}
,
"b_duration":4,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"SW",
"position_bu":{
"FP":"0",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":""}
,
"XY":{
"x":"0.000000",
"y":"1.000000"}
,
"DocXY":{
"x":"0.000000",
"y":"0.000000"}
,
"Off":{
"x":6,
"y":4}
}
,
"show_hl_d":true,
"show_hl_p":true,
"show_bubble_d":true,
"show_bubble_p":true,
"click_pos":{
"left":1582,
"top":59}
,
"click_count":1,
"exec_mouse":false,
"hotspot_client_rect":{
"left":-2147483648,
"top":-2147483648,
"width":0,
"height":0}
,
"ctl_rect":{
"left":1572,
"top":1,
"width":21,
"height":822}
,
"cursor_hand":true,
"ctl_button":false,
"ctl_tooltip":""}
]
}
,{
"index":26,
"title":"Client Portal - Planning Forms - Brave",
"audio":"",
"uid":"TS_011B432D509740CAB61F57BEAD16BE94",
"jumpable":true,
"visible":false,
"callable":false,
"duration":29,
"audio_duration":0,
"macros":[
{
"macro_template":"new_page",
"time":0,
"duration":10,
"uid":"MAC_BC6063AAE9643CBA",
"new_step":"Client Portal - Planning Forms - Brave",
"dump_page":"dump_page\\",
"dump_page_size":{
"width":1596,
"height":824}
,
"alt_txt":"",
"screenshot_rect":{
"left":0,
"top":0,
"width":1596,
"height":824}
,
"context":""}
,{
"macro_template":"explanation_long",
"time":9,
"duration":10,
"uid":"MAC_F9F82C8A2FB38F89",
"all_like_demo":false,
"explanation_d":"<p>This concludes our Forms demonstration. You should now know how to view and edit forms in the Portal.<\/p>\n",
"explanation_p":"<p>This concludes our Forms demonstration. You should now know how to view and edit forms in the Portal.<\/p>\n",
"type":"info",
"bubblestyle_d":"sap_gold",
"b_width":459,
"b_height":174,
"orientation":"C",
"position_b":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"b_duration":-1,
"bubblestyle_p":"sap_gold",
"b_width_p":180,
"b_height_p":40,
"orientation_p":"C",
"position_bu":{
"FP":"",
"elem":{
"EP":"",
"coll":"\"\"",
"idx":0,
"subidx":0,
"id":"page"}
,
"XY":{
"x":"0.499977",
"y":"0.499977"}
,
"DocXY":{
"x":"0.499977",
"y":"0.499977"}
}
,
"in_demo":true,
"in_practice":true,
"in_test":false,
"in_prax":true,
"show_nav_buttons":true,
"show_hl_doc":false}
,{
"macro_template":"end_unit",
"time":19,
"duration":10,
"macro_comment":"",
"uid":"MAC_EDC6EA0E31D9F599"}
]
}
]
}
